#!/usr/bin/env bash

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

# Redirect STDERR to STDOUT
exec 2>&1

#
POSTGRES_HOST=$(env_get "POSTGRES_HOST")
MYSQL_HOST=$(env_get "MYSQL_HOST")
DATABASE_HOST=${MYSQL_HOST:=$POSTGRES_HOST}
NEXTCLOUD_USER=${NEXTCLOUD_USER}

# Wait for database connection
if [ -n "$DATABASE_HOST" ]; then

    host=$(echo $DATABASE_HOST | cut -d ":" -f 1)
    port=$(echo $DATABASE_HOST | cut -d ":" -f 2)

    wait-host "${host}:${port}" \
        -t 0 \
        -d 2 \
        -m "Waiting for database connection on host: ${host} and port: ${port}" \
        -s

    if [ $? ]; then
        NOTICE "Database connection established on host: ${host} and port: ${port}"
    else
        WARNING "Error while trying to connect to the database"
    fi

fi

# Start nextcloud
NOTICE ''
NOTICE 'Starting Nextcloud'
exec su-exec ${NEXTCLOUD_USER} php-fpm

# This exit code will be sent as the first parameter to the finish script
exit 1

