#!/usr/bin/env bash

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

# Redirect STDERR to STDOUT
exec 2>&1

# Start nextcloud
NOTICE ''
NOTICE 'Starting Nextcloud'
exec su-exec ${NEXTCLOUD_USER} php-fpm

# This exit code will be sent as the first parameter to the finish script
exit 1

